apoe4:
  hap_files: resources/hap_files
  haps: ["APOe4", "rs429358-rs7412"]
  causal_hap: "APOe4"
  genotypes: resources/1000G_chr19.vcf.gz
  betas: [0.2, 0.3, 0.4]
  heritabilities: [0.4]
  region: 19:45412010
ancestry:
  reference: resources/1000G_chr1.vcf.gz
  sample_info: resources/1000G_AfrAmerican_sampleinfo.tsv
  models:
    Admixed: resources/1000G_AfrAmerican_model.dat
    YRI: resources/1000G_YRI_model.dat
    CEU: resources/1000G_CEU_model.dat
  mapdir: resources/map
  snp: 1:109274968
  hap: resources/rs12740374.hap.gz
  betas: [0.01, 0.02, 0.03, 0.04, 0.045, 0.05, 0.055, 0.06, 0.07, 0.08, 0.09, 0.1]
  replicates: 100
