channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bioconda::plink2
  - conda-forge::matplotlib
  - conda-forge::pandas
  - conda-forge::click
  - conda-forge::numpy
  - conda-forge::statsmodels
  - conda-forge::pip
  - pip:
    - git+https://github.com/gymrek-lab/haptools.git@ref/simphenotype
