channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bioconda::plink2==2.00a2.3
  - conda-forge::matplotlib==3.5.2
  - conda-forge::pandas==1.4.3
  - conda-forge::click==8.1.3
  - conda-forge::numpy==1.23.1
  - conda-forge::statsmodels==0.13.2
  - conda-forge::pip
  - pip:
    - git+https://github.com/gymrek-lab/haptools.git
